apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
  namespace: default
  labels:
    app: hello-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      containers:
        - name: hello-api
          image: ECR_IMAGE_REPOSITORY:ECR_IMAGE_TAG
          tty: true
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: "1Gi"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: external-lb
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: hello-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: ingress-hello-api
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/healthcheck-path: /api/hello
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-lb
                port:
                  number: 80
